-- INSERT INTO USERS
-- VALUES(1, 20, 'matthys.sven@gmail.com', 'testpassword', 'Sven', '0', 'Matthys', 'SveNord');
--
-- INSERT INTO USERS
-- VALUES(2, 20, 'gino.moukhi@gmail.com', 'testpasswordGINO', 'Gino', '0', 'Moukhi', 'LoneWolf');
--
